### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by idleberg** [Robbatron/drag-relative-path#2]
[Enter steps to reproduce below:]

1. I installed the plugin and restarted Atom
2. I create a new HTML document
3. Now, whether I drag a file from the desktop or the tree view, I get the following error

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.9.5
**Thrown From**: [drag-relative-path](https://github.com/Robbatron/drag-relative-path) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/me/.atom/packages/drag-relative-path/lib/drag-relative-path.coffee:53

TypeError: Cannot read property 'split' of undefined
    at atom-text-editor.<anonymous> (/Users/me/.atom/packages/drag-relative-path/lib/drag-relative-path.coffee:53:51)
```

### Commands

```
     -0:09.3.0 tree-view:toggle (input.hidden-input)
     -0:05.0 command-palette:toggle (input.hidden-input)
     -0:04.2.0 core:confirm (input.hidden-input)
     -0:04.2.0 set-syntax:HTML (input.hidden-input)
```

**Comment by Robbatron** [comment]
Thanks for the detailed report, oddly I cannot replicate it. Can you share the name of the file you were trying to drag when you got the error? It either is having a hard time getting the extension from the current path or finding the active text editor.

**Comment by idleberg** [comment]
It works fine on my computer at home (macOS 10.12.2), so we'll have to wait for Monday to come, so I can test it on my computer at work.

By the way, do you think it's possible to drag the image to a certain position in the code? Currently, the tag gets created where the cursor resides before dragging.

**Comment by idleberg** [comment]
Here's another observation. The same problem occurs (even at my home computer) when I drop a folder onto my Atom window, which is something I often do to load a projects. There should be an additional check whether a file has been dropped.

**Comment by Robbatron** [comment]
Can you update to v1.0.2 and see if that fixes your issues? I don't believe the Atom API provides any functionality to drag to a certain position but it also didn't provide any functionality to drag from tree-view, so there is probably a way to hack around it. I have a few busy weeks coming up but will try to figure it out when I get a chance.

**Comment by idleberg** [comment]
I can now drag & drop folders, but (at work) I still get errors when dragging images, JavaScript or CSS.

Same error, only the line changed:

```
TypeError: Cannot read property 'split' of undefined
    at atom-text-editor.<anonymous> (/Users/me/.atom/packages/drag-relative-path/lib/drag-relative-path.coffee:64:61)
```

Will do another test at home!

**Comment by Robbatron** [comment]
Thank you for being patient. Are you trying to drag the JS, CSS, and IMG files into an HTML file? I get an error at the same position if I try to drag them into an untitled tab, which is not supported by this package.

**Comment by idleberg** [comment]
That was it, I dragged them into an untitled tab

**Comment by Robbatron** [comment]
Good insight. Since I do not want to mess with Atom's default behavior, I just pushed a patch that will prevent an error from being thrown in that scenario. I hope that takes care of the Uncaught TypeError for you!

**Comment by idleberg** [comment]
Thanks! I guess we can close this.
