### ISSUE TITLE
Drag to other than html

### ISSUE THREAD

**Issue by ericvida** [Robbatron/drag-relative-path#4]
Can you modify this so that it will drag to css, sass, pug(jade) files as well?
Is it possible also to allow selection of multiple files from the file tree and drag them all at once? That would be rad.

**Comment by Robbatron** [comment]
Sorry for the late response! Do you want to drag relative paths without the html tags to css, sass, and pug files? The multiple file approach sounds doable 🤔 I'll look into it when I get a moment!

**Comment by ericvida** [comment]
Coda 2 allows you to select multiple files in the file tree and drag into any document (holding option) and it will dump all the relative paths into the document no matter what language it is. Then with multi-line editing, is really easy to put a whole stack of paths into anchor or img tags. It’s a charm. I build quite elaborate static sites using pug, I create blog like pages by including tons of article.pug files, so when it gets to the dozens or hundred’s I jump into coda to use their drag and drop feature. Your plug-in makes it faster than typing it, but it’d be great if it supported dragging multiple items.

So yeah, without tags is great because I can use the path for anything I’d like.

**Comment by Robbatron** [comment]
Thanks for the description. Coda 2 sounds great! Atom has extremely minimal support for Drag-and-Drop actions, especially between the file tree and the text editor pane, so to even make this plugin work I had to do some hacky things with the DOM. This does seem doable though. Real quick, is something like this kind of what you want? 

![test3](https://cloud.githubusercontent.com/assets/6432957/24106484/38ea46a6-0d45-11e7-87c5-e820a9c6a7a1.gif)

**Comment by ericvida** [comment]
YES!!!!! I did notice that electron framework is a little limited on how it can interact with files, but man you almost got it.
If they can be in separate lines it would be exactly what I’m looking for. It would be the best drag and drop plug-in for atom.
If they’re all in separate lines, I can use multiple cursors to wrap them all in the desired tags all at once.

**Comment by ericvida** [comment]
Also, can atom plug-ins be easily repackaged for visual studio code?

**Comment by iamtirado** [comment]
Coda doesn’t support pug syntax highlighting, but here's an example of how I’d use this feature in coda.
https://cl.ly/1Q2L2s10013E

—
Eric Tirado
Brand Design | Web Development
erictirado1@gmail.com
678-577-8064

**Comment by ericvida** [comment]
Here's a real world example. I'm building a site with an articles directory, and dozens (if not hundreds) of articles will be included into different pages. In this example, I show (with two paths), what I'd like to do with dozens of them if I could drag them all into the document in different lines.
![drag-and-drop](https://cloud.githubusercontent.com/assets/13579055/24117488/d56782b0-0d80-11e7-9075-5759bfab2971.gif)
@Robbatron

**Comment by Robbatron** [comment]
I made the changes to allow for multiple relative paths to be inserted on separate lines (and even added the capability to generate multiple HTML tags at once) but am mildly annoyed with how Atom behaves when multiple files are selected. 

It is only possible to drag multiple files from the tree by selecting them each with Command/Ctrl then dragging them to the text pane with Shift. Unfortunately, Shift highlights the whole range of files. Here is an example of what I mean...


![drp](https://cloud.githubusercontent.com/assets/6432957/24180505/8457015a-0e72-11e7-9419-eaff0c2ecdaa.gif)


If this is sufficient then I will push the changes, but it does look like the files you want to include are in a folder with some other files. Can you think of a way to drag them without holding Shift?

I'll also look into porting it to vscode!

**Comment by ericvida** [comment]
Not sure what you mean by "without holding shift". 
I don't need to use shift for dragging. That looks perfect to me. Are you saying that atom only allows you to drag and drop while using "shift" key?

**Comment by Robbatron** [comment]
Yes, maybe it's just a weird keybinding issue on my end. I cannot drag _multiple_ files without holding shift - single files are not an issue. I will push these changes when I get a moment. Thank you for your help.

**Comment by ericvida** [comment]
I see. I will try it when it's up and let you know. Thank you for your work.

**Comment by Robbatron** [comment]
No problem. You can download v1.1.0 now. I hope this feature further enhances your development experience so that you can keep on making cool stuff!

**Comment by ericvida** [comment]
This package below allows me to drag without holding shift. Maybe you can integrate it with your package somehow or let people know they should install it. The issue is that atom will try to open anything you click on with a single click, and that interferes with with the click and drag.
- https://github.com/h2so5/atom-chary-tree-view

But I can get it to work. I love it.
![screen recording 2017-03-23 at 09 42 am](https://cloud.githubusercontent.com/assets/13579055/24250400/29532c70-0fad-11e7-9d5a-0954c426198d.gif)


Quirks I found (which you may not be able to do anything about):
- I have to click on the last file I want to drag in my `command` or `shift` selection, without letting go of `command` or `shift` keys and immediately begin dragging without releasing the keys or click, BUT then I need to let go of `command` or `shift` before releasing the click or it won't paste. It would be less quirky if I didn't have to release command or shift to paste. Can you make it so that it has no issue with holding shift or command while releasing click?

- Indentation. Anything after the second line will be indented 4 spaces. No sure if it can be done so they're all with no spaces.
