### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by PixelT** [Robbatron/drag-relative-path#5]
Set 2 columns layout in atom.
Open some files.
Try to move file from left to right column.

```
Uncaught TypeError: Cannot read property 'dataset' of null
```

**Comment by Robbatron** [comment]
Hey, thanks for opening this issue and helping me improve this plugin! I cannot seem to replicate this error, can you post a gif or alternate instructions on how to replicate this?

**Comment by cliffordfajardo** [comment]
I'm also experiecing the error when dragging tabs to create a N-column layout
![apr-05-2017 11-32-01](https://cloud.githubusercontent.com/assets/6743796/24720947/9f7cf46c-19f3-11e7-95c4-098fd48a1ecd.gif)

**Comment by Robbatron** [comment]
Awesome, thanks for the demonstration. I will look into it this weekend.

**Comment by Robbatron** [comment]
Hi, I have tried on multiple occasions to replicate this error but I simply cannot. I have put an additional check on line 80 to see if the selector exists and is not null before deriving its dataset, so I will push the change with a few others and hopefully it solves your issue. If not, feel free to submit a pull request or report back with additional use cases! Thank you for helping me improve this plugin. 


![drp](https://cloud.githubusercontent.com/assets/6432957/26667405/ed402592-4659-11e7-9d72-a82a41b978e0.gif)

**Comment by Robbatron** [comment]
@PixelT @cliffordfajardo As of v1.1.3 I am no longer able to replicate this issue. If I do not hear back by 8/14 I will assume that this is no longer a problem and close this issue. Thanks.
