### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by seyhaheng2** [Robbatron/drag-relative-path#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [drag-relative-path](https://github.com/Robbatron/drag-relative-path) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/sino/.atom/packages/drag-relative-path/lib/drag-relative-path.coffee:81

TypeError: Cannot read property 'file' of undefined
    at /packages/drag-relative-path/lib/drag-relative-path.coffee:81:145)
```

### Commands

```
     -1:58.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate)
     -1:27 core:undo (input.hidden-input)
```

### Non-Core Packages

```
autoprefixer 3.6.1 
comment 0.6.1 
drag-relative-path 1.1.0 
emmet 2.4.3 
ex-mode 0.14.0 
file-icons 2.1.4 
highlight-selected 0.13.1 
html2haml 0.10.0 
language-haml 0.24.1 
minimap 4.28.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-vim 0.2.3 
pigments 0.39.1 
rails-latest-migration 1.1.6 
rails-partials 0.9.2 
rails-snippets 2.15.0 
scss-media-queries 0.4.0 
scss-snippets 0.6.0 
seti-icons 1.4.3 
seti-syntax 1.1.3 
seti-ui 1.7.0 
vim-mode 0.66.0 
vim-surround 0.8.1 
```

**Comment by ericvida** [comment]
having same issue. drag and drop no longer working.

**Comment by Robbatron** [comment]
I believe this is related to issue 5 (https://github.com/Robbatron/drag-relative-path/issues/5), which I have implemented an additional check for. I cannot replicate this issue and may need some additional information. What type of file are you trying to drag from the tree-view? Are you trying to drag it into an untitled tab? Feel free to submit a pull request if you can replicate and want to propose a code fix! Thanks for helping me make this plugin better.

**Comment by dariusgarza** [comment]
Also having the same issue :(

**Comment by foundry** [comment]
I am seeing the same issue - with various file types: jpg, .md, .css, .html
Atom: 1.18.0 x64
OSX: 10.12.4
`/Volumes/jHome/.atom/packages/drag-relative-path/lib/drag-relative-path.coffee:82`

**Comment by Robbatron** [comment]
Thank you, everyone. I am aware that this is an issue but have not had time to look into it. Would anyone mind submitting a PR?

**Comment by Robbatron** [comment]
@seyhaheng2 @iamtirado @dariusgarza @foundry Made some fixes. Can you check if your problem is solved by v1.1.3?

**Comment by Robbatron** [comment]
@seyhaheng2 @iamtirado @dariusgarza @foundry As of v1.1.3 I am no longer able to replicate this issue. If I do not hear back by 8/14 I will assume that this is no longer a problem and close this issue. Thanks.

**Comment by dariusgarza** [comment]
Thanks @Robbatron for looking into the issue. Im still having problems unfortunately. Any suggestions?

`Uncaught TypeError: Cannot read property 'path' of null`
`TypeError: Cannot read property 'path' of null
    at HTMLElement.<anonymous> (/Users/Darius/.atom/packages/drag-relative-path/lib/drag-relative-path.coffee:67:55)`

**Comment by Robbatron** [comment]
@dariusgarza Absolutely, thank you for your help. First, are you updated to v1.1.3? If so, what type of files are you trying to drag from and into?
