### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by holger-dev** [Robbatron/drag-relative-path#7]
Hi!
I just installed the package but nothing happen when i drag and drop files - ver. 1.1.2 and actual Atom-Version 1.18 under windows 10. Are there any plugins/packages need for? THX!

**Comment by junglized** [comment]
The same here. When dragging an icon with file path is being displayed but when I drop it no path is being inserted. That feature would be a great asset for my Atom install. I use Atom 1.18.0.

**Comment by Robbatron** [comment]
@htrampe @junglized Made some fixes. Can you check if your problem is solved by v1.1.3?

**Comment by Robbatron** [comment]
@htrampe @junglized After v1.1.3 I am no longer able to replicate this issue. If I do not hear back by 8/14 I will assume that this is no longer a problem and close this issue. Thanks.
